<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class AdmissionRuleSeeder extends Seeder
{
    public function run(): void
    {
        $lifeOrientationSubjectId = DB::table('subjects')
            ->join('grades', 'grades.id', '=', 'subjects.grade_id')
            ->join('curriculums', 'curriculums.id', '=', 'subjects.curriculum_id')
            ->where('curriculums.abbreviation', 'CAPS')
            ->where('grades.name', 'Grade 12')
            ->where('subjects.name', 'Life Orientation')
            ->value('subjects.id');

        $nscLevels = [
            ['level' => 7, 'label' => 'Outstanding Achievement', 'minimum_mark' => 80, 'maximum_mark' => 100, 'points' => 7],
            ['level' => 6, 'label' => 'Meritorious Achievement', 'minimum_mark' => 70, 'maximum_mark' => 79, 'points' => 6],
            ['level' => 5, 'label' => 'Substantial Achievement', 'minimum_mark' => 60, 'maximum_mark' => 69, 'points' => 5],
            ['level' => 4, 'label' => 'Adequate Achievement', 'minimum_mark' => 50, 'maximum_mark' => 59, 'points' => 4],
            ['level' => 3, 'label' => 'Moderate Achievement', 'minimum_mark' => 40, 'maximum_mark' => 49, 'points' => 3],
            ['level' => 2, 'label' => 'Elementary Achievement', 'minimum_mark' => 30, 'maximum_mark' => 39, 'points' => 2],
            ['level' => 1, 'label' => 'Not achieved', 'minimum_mark' => 0, 'maximum_mark' => 29, 'points' => 1],
        ];
        $spuBasePoints = [
            ['minimum_mark' => 90, 'maximum_mark' => 100, 'points' => 8],
            ['minimum_mark' => 80, 'maximum_mark' => 89, 'points' => 7],
            ['minimum_mark' => 70, 'maximum_mark' => 79, 'points' => 6],
            ['minimum_mark' => 60, 'maximum_mark' => 69, 'points' => 5],
            ['minimum_mark' => 50, 'maximum_mark' => 59, 'points' => 4],
            ['minimum_mark' => 40, 'maximum_mark' => 49, 'points' => 3],
            ['minimum_mark' => 30, 'maximum_mark' => 39, 'points' => 2],
            ['minimum_mark' => 0, 'maximum_mark' => 29, 'points' => 1],
        ];
        $spuMathematicsAndLanguagePoints = [
            ['minimum_mark' => 90, 'maximum_mark' => 100, 'points' => 10],
            ['minimum_mark' => 80, 'maximum_mark' => 89, 'points' => 9],
            ['minimum_mark' => 70, 'maximum_mark' => 79, 'points' => 8],
            ['minimum_mark' => 60, 'maximum_mark' => 69, 'points' => 7],
            ['minimum_mark' => 50, 'maximum_mark' => 59, 'points' => 5],
            ['minimum_mark' => 40, 'maximum_mark' => 49, 'points' => 4],
            ['minimum_mark' => 30, 'maximum_mark' => 39, 'points' => 2],
            ['minimum_mark' => 0, 'maximum_mark' => 29, 'points' => 1],
        ];
        $spuLifeOrientationPoints = [
            ['minimum_mark' => 90, 'maximum_mark' => 100, 'points' => 4],
            ['minimum_mark' => 80, 'maximum_mark' => 89, 'points' => 3],
            ['minimum_mark' => 70, 'maximum_mark' => 79, 'points' => 2],
            ['minimum_mark' => 60, 'maximum_mark' => 69, 'points' => 1],
            ['minimum_mark' => 0, 'maximum_mark' => 59, 'points' => 0],
        ];
        $spuMathematicsAndLanguageSubjects = [
            'Mathematics',
            'Afrikaans Home Language',
            'Afrikaans First Additional Language',
            'English Home Language',
            'English First Additional Language',
            'isiNdebele Home Language',
            'isiNdebele First Additional Language',
            'isiXhosa Home Language',
            'isiXhosa First Additional Language',
            'isiZulu Home Language',
            'isiZulu First Additional Language',
            'Sepedi Home Language',
            'Sepedi First Additional Language',
            'Sesotho Home Language',
            'Sesotho First Additional Language',
            'Setswana Home Language',
            'Setswana First Additional Language',
            'SiSwati Home Language',
            'SiSwati First Additional Language',
            'Tshivenda Home Language',
            'Tshivenda First Additional Language',
            'Xitsonga Home Language',
            'Xitsonga First Additional Language',
        ];

        $rules = [
            [
                'code' => 'nsc_aps_excluding_lo',
                'name' => 'NSC APS excluding Life Orientation',
                'score_type' => 'aps',
                'calculation_method' => 'aps_level_sum',
                'score_label' => 'APS',
                'score_suffix' => null,
                'max_score' => 42,
                'include_life_orientation' => false,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => $nscLevels,
                'config' => ['excluded_subjects' => ['Life Orientation']],
                'description' => 'Adds NSC achievement levels for all available subjects except Life Orientation.',
            ],
            [
                'code' => 'nsc_aps_including_lo',
                'name' => 'NSC APS including Life Orientation',
                'score_type' => 'aps',
                'calculation_method' => 'aps_level_sum',
                'score_label' => 'APS',
                'score_suffix' => null,
                'max_score' => 49,
                'include_life_orientation' => true,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => $nscLevels,
                'config' => ['included_subjects' => ['Life Orientation']],
                'description' => 'Adds NSC achievement levels for all available subjects, including Life Orientation.',
            ],
            [
                'code' => 'nsc_aggregate_excluding_lo',
                'name' => 'NSC aggregate average excluding Life Orientation',
                'score_type' => 'aggregate_average',
                'calculation_method' => 'average_mark',
                'score_label' => 'Aggregated average',
                'score_suffix' => '%',
                'max_score' => 100,
                'include_life_orientation' => false,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => ['excluded_subjects' => ['Life Orientation']],
                'description' => 'Averages available marks, excluding Life Orientation.',
            ],
            [
                'code' => 'nsc_aggregate_including_lo',
                'name' => 'NSC aggregate average including Life Orientation',
                'score_type' => 'aggregate_average',
                'calculation_method' => 'average_mark',
                'score_label' => 'Aggregated average',
                'score_suffix' => '%',
                'max_score' => 100,
                'include_life_orientation' => true,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => ['included_subjects' => ['Life Orientation']],
                'description' => 'Averages available marks, including Life Orientation.',
            ],
            [
                'code' => 'nmu_applicant_score',
                'name' => 'NMU Applicant Score',
                'score_type' => 'applicant_score',
                'calculation_method' => 'nmu_applicant_score',
                'score_label' => 'AS',
                'score_suffix' => null,
                'max_score' => 600,
                'include_life_orientation' => false,
                'subject_count' => 6,
                'subject_selection_strategy' => 'nmu_fundamentals_then_best',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'excluded_subjects' => ['Life Orientation'],
                    'fundamental_subjects' => [
                        'home_language',
                        'first_additional_language',
                        'mathematics_or_mathematical_literacy_or_technical_mathematics',
                    ],
                    'life_orientation_bonus' => [
                        'enabled' => true,
                        'points' => 7,
                        'minimum_mark' => 50,
                        'school_quintiles' => [1, 2, 3],
                        'requires_school_quintile_data' => true,
                    ],
                ],
                'description' => 'Nelson Mandela University Applicant Score out of 600: add percentages for six subjects excluding Life Orientation, forcing Home Language, First Additional Language and Mathematics/Mathematical Literacy/Technical Mathematics into the score. A 7-point Life Orientation bonus applies only for qualifying quintile 1-3 schools when school quintile data is available.',
            ],
            [
                'code' => 'percentage_aps_6_excluding_lo',
                'name' => 'Percentage APS from six subjects excluding Life Orientation',
                'score_type' => 'aps',
                'calculation_method' => 'raw_mark_sum',
                'score_label' => 'APS',
                'score_suffix' => null,
                'max_score' => 60,
                'include_life_orientation' => false,
                'subject_count' => 6,
                'subject_selection_strategy' => 'best_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'excluded_subjects' => ['Life Orientation'],
                    'score_divisor' => 10,
                    'automatic_acceptance_threshold' => 45,
                    'deans_discretion_range' => ['minimum' => 36, 'maximum' => 44],
                ],
                'description' => 'Adds six subject percentages excluding Life Orientation and divides by 10. Used by Rhodes-style APS calculations.',
            ],
            [
                'code' => 'uct_fps_600_excluding_lo',
                'name' => 'UCT FPS out of 600 excluding Life Orientation',
                'score_type' => 'fps',
                'calculation_method' => 'raw_mark_sum',
                'score_label' => 'FPS',
                'score_suffix' => null,
                'max_score' => 600,
                'include_life_orientation' => false,
                'subject_count' => 6,
                'subject_selection_strategy' => 'best_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'excluded_subjects' => ['Life Orientation'],
                    'disadvantage_factor_supported' => true,
                ],
                'description' => 'Sums six NSC percentages excluding Life Orientation. Used by UCT Commerce, Engineering and the Built Environment, Humanities and Law before weighting.',
            ],
            [
                'code' => 'uct_fps_800_science',
                'name' => 'UCT Science FPS out of 800',
                'score_type' => 'fps',
                'calculation_method' => 'weighted_mark_sum',
                'score_label' => 'FPS',
                'score_suffix' => null,
                'max_score' => 800,
                'include_life_orientation' => false,
                'subject_count' => 6,
                'subject_selection_strategy' => 'best_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'excluded_subjects' => ['Life Orientation'],
                    'additional_subject_weights' => [
                        ['subject' => 'Mathematics', 'additional_weight' => 1],
                        ['subject' => 'Physical Sciences', 'additional_weight' => 1],
                    ],
                    'disadvantage_factor_supported' => true,
                ],
                'description' => 'Sums six NSC percentages excluding Life Orientation, then adds Mathematics and Physical Sciences again.',
            ],
            [
                'code' => 'uct_fps_900_health_sciences',
                'name' => 'UCT Health Sciences FPS out of 900',
                'score_type' => 'fps',
                'calculation_method' => 'composite_sum',
                'score_label' => 'FPS',
                'score_suffix' => null,
                'max_score' => 900,
                'include_life_orientation' => false,
                'subject_count' => 6,
                'subject_selection_strategy' => 'best_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'components' => [
                        ['method' => 'raw_mark_sum', 'label' => 'APS/FPS school marks', 'max_score' => 600],
                        ['method' => 'external_sum', 'label' => 'NBT AL, QL and MAT', 'max_score' => 300, 'required' => true],
                    ],
                    'excluded_subjects' => ['Life Orientation'],
                    'disadvantage_factor_supported' => true,
                ],
                'description' => 'UCT Health Sciences FPS: school marks out of 600 plus NBT scores out of 300.',
            ],
            [
                'code' => 'nsc_pass_type',
                'name' => 'NSC pass type',
                'score_type' => 'pass_type',
                'calculation_method' => 'nsc_pass_type',
                'score_label' => 'NSC pass type',
                'score_suffix' => null,
                'max_score' => null,
                'include_life_orientation' => false,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'ranking' => ['none' => 0, 'nsc' => 1, 'higher_certificate' => 2, 'diploma' => 3, 'bachelor' => 4],
                    'rules' => [
                        'bachelor' => ['home_language_minimum' => 40, 'subjects_at_50_excluding_lo' => 4, 'remaining_subjects_minimum' => 30],
                        'diploma' => ['home_language_minimum' => 40, 'subjects_at_40_excluding_lo' => 3, 'remaining_subjects_minimum' => 30],
                        'higher_certificate' => ['home_language_minimum' => 40, 'subjects_at_40' => 2, 'remaining_subjects_minimum' => 30],
                        'nsc' => ['home_language_minimum' => 40, 'subjects_at_40' => 2, 'subjects_at_30' => 3],
                    ],
                ],
                'description' => 'Determines whether the learner has an NSC, Higher Certificate, Diploma or Bachelor pass.',
            ],
            [
                'code' => 'senior_certificate_pass',
                'name' => 'Senior Certificate pass',
                'score_type' => 'pass_type',
                'calculation_method' => 'senior_certificate_pass',
                'score_label' => 'Senior Certificate',
                'score_suffix' => null,
                'max_score' => null,
                'include_life_orientation' => true,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => 'senior_certificate',
                'points_scale' => null,
                'config' => [
                    'ranking' => ['none' => 0, 'senior_certificate' => 1],
                    'rules' => [
                        'subjects_at_40' => 3,
                        'home_language_at_40' => 1,
                        'subjects_at_30' => 5,
                        'language_at_30' => 1,
                        'subjects_at_20' => 6,
                    ],
                ],
                'description' => 'Senior Certificate promotion requirement: three subjects at 40% including a Home Language, two more subjects at 30% including a language, and at least 20% in the sixth subject.',
            ],
            [
                'code' => 'wits_aps',
                'name' => 'Wits APS',
                'score_type' => 'aps',
                'calculation_method' => 'subject_point_sum',
                'score_label' => 'Wits APS',
                'score_suffix' => null,
                'max_score' => 56,
                'include_life_orientation' => true,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'source_note' => 'Wits awards extra APS points for English and Mathematics, and a reduced Life Orientation score.',
                    'subject_point_scales' => [
                        [
                            'label' => 'English and Mathematics',
                            'subjects' => [
                                'English Home Language',
                                'English First Additional Language',
                                'Mathematics',
                            ],
                            'bands' => [
                                ['minimum_mark' => 90, 'maximum_mark' => 100, 'points' => 10],
                                ['minimum_mark' => 80, 'maximum_mark' => 89, 'points' => 9],
                                ['minimum_mark' => 70, 'maximum_mark' => 79, 'points' => 8],
                                ['minimum_mark' => 60, 'maximum_mark' => 69, 'points' => 7],
                                ['minimum_mark' => 50, 'maximum_mark' => 59, 'points' => 4],
                                ['minimum_mark' => 40, 'maximum_mark' => 49, 'points' => 3],
                                ['minimum_mark' => 0, 'maximum_mark' => 39, 'points' => 0],
                            ],
                        ],
                        [
                            'label' => 'Life Orientation',
                            'subjects' => ['Life Orientation'],
                            'bands' => [
                                ['minimum_mark' => 90, 'maximum_mark' => 100, 'points' => 4],
                                ['minimum_mark' => 80, 'maximum_mark' => 89, 'points' => 3],
                                ['minimum_mark' => 70, 'maximum_mark' => 79, 'points' => 2],
                                ['minimum_mark' => 60, 'maximum_mark' => 69, 'points' => 1],
                                ['minimum_mark' => 0, 'maximum_mark' => 59, 'points' => 0],
                            ],
                        ],
                    ],
                    'default_point_scale' => [
                        'label' => 'Other subjects',
                        'bands' => [
                            ['minimum_mark' => 90, 'maximum_mark' => 100, 'points' => 8],
                            ['minimum_mark' => 80, 'maximum_mark' => 89, 'points' => 7],
                            ['minimum_mark' => 70, 'maximum_mark' => 79, 'points' => 6],
                            ['minimum_mark' => 60, 'maximum_mark' => 69, 'points' => 5],
                            ['minimum_mark' => 50, 'maximum_mark' => 59, 'points' => 4],
                            ['minimum_mark' => 40, 'maximum_mark' => 49, 'points' => 3],
                            ['minimum_mark' => 0, 'maximum_mark' => 39, 'points' => 0],
                        ],
                    ],
                ],
                'description' => 'Wits APS from NSC percentages: English and Mathematics receive boosted points, Life Orientation counts on a reduced scale, and other subjects use the Wits APS subject scale.',
            ],
            [
                'code' => 'spu_admission_points',
                'name' => 'Sol Plaatje University Admission Point Score',
                'score_type' => 'aps',
                'calculation_method' => 'subject_point_sum',
                'score_label' => 'SPU APS',
                'score_suffix' => null,
                'max_score' => 58,
                'include_life_orientation' => true,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => [
                    'source_note' => 'SPU awards 8 to 1 points by NSC percentage band, adds points for Mathematics and languages, and counts Life Orientation on a reduced 4 to 0 scale.',
                    'source_url' => 'https://www.spu.ac.za/index.php/admission-requirements-2/',
                    'additional_points' => [
                        'Mathematics and languages (HL/FAL)' => [
                            ['minimum_mark' => 60, 'maximum_mark' => 100, 'points' => 2],
                            ['minimum_mark' => 40, 'maximum_mark' => 59, 'points' => 1],
                            ['minimum_mark' => 0, 'maximum_mark' => 39, 'points' => 0],
                        ],
                    ],
                    'subject_point_scales' => [
                        [
                            'label' => 'Mathematics and languages',
                            'subjects' => $spuMathematicsAndLanguageSubjects,
                            'bands' => $spuMathematicsAndLanguagePoints,
                        ],
                        [
                            'label' => 'Life Orientation',
                            'subjects' => ['Life Orientation'],
                            'bands' => $spuLifeOrientationPoints,
                        ],
                    ],
                    'default_point_scale' => [
                        'label' => 'Other subjects',
                        'bands' => $spuBasePoints,
                    ],
                ],
                'description' => 'Sol Plaatje University Admission Point Score: NSC percentage bands with extra points for Mathematics and languages, and reduced Life Orientation points.',
            ],
            [
                'code' => 'subject_levels_only',
                'name' => 'Subject levels only',
                'score_type' => 'subject_levels',
                'calculation_method' => 'none',
                'score_label' => 'Subject levels',
                'score_suffix' => null,
                'max_score' => null,
                'include_life_orientation' => true,
                'subject_count' => null,
                'subject_selection_strategy' => 'all_subjects',
                'minimum_pass_type' => null,
                'points_scale' => null,
                'config' => ['score_required' => false],
                'description' => 'Uses only per-subject minimum marks or levels. Useful for colleges and courses that do not publish an APS.',
            ],
        ];

        foreach ($rules as $rule) {
            $code = $rule['code'];
            unset($rule['code']);

            DB::table('admission_rules')->updateOrInsert(
                ['code' => $code],
                array_merge($rule, [
                    'life_orientation_subject_id' => $lifeOrientationSubjectId,
                    'points_scale' => $rule['points_scale'] === null ? null : json_encode($rule['points_scale']),
                    'config' => $rule['config'] === null ? null : json_encode($rule['config']),
                    'is_active' => true,
                    'created_at' => now(),
                    'updated_at' => now(),
                ]),
            );
        }
    }
}
