<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class BursarySeeder extends Seeder
{
    public function run(): void
    {
        $now = now();
        $grade12Id = DB::table('grades')->where('name', 'Grade 12')->value('id');
        $subjectIds = DB::table('subjects')
            ->join('grades', 'grades.id', '=', 'subjects.grade_id')
            ->join('curriculums', 'curriculums.id', '=', 'subjects.curriculum_id')
            ->where('grades.name', 'Grade 12')
            ->where('curriculums.abbreviation', 'CAPS')
            ->pluck('subjects.id', 'subjects.name');

        $company = fn (
            string $name,
            ?string $website = null,
            ?string $description = null,
            ?string $contactEmail = null,
            ?string $contactPhone = null,
        ): array => [
            'name' => $name,
            'website' => $website,
            'description' => $description,
            'contact_email' => $contactEmail,
            'contact_phone' => $contactPhone,
        ];

        $bursary = fn (array $data): array => array_merge([
            'service_contract' => null,
            'renewal' => null,
            'contact_name' => null,
            'contact_email' => null,
            'contact_phone' => null,
            'apply_url' => null,
            'is_active' => true,
        ], $data);

        $entry = fn (array $company, array $bursary, array $requirements = []): array => [
            'company' => $company,
            'bursary' => $bursary,
            'subject_requirements' => $requirements,
        ];

        $req = function (
            ?string $subjectName,
            ?int $minimumMark = null,
            string $type = 'required',
            ?string $group = null,
            ?string $notes = null,
            ?int $apsLevel = null,
        ) use ($subjectIds): array {
            return [
                'subject_name' => $subjectName,
                'subject_id' => $subjectName !== null ? ($subjectIds[$subjectName] ?? null) : null,
                'minimum_mark' => $minimumMark,
                'aps_level_required' => $apsLevel,
                'requirement_type' => $type,
                'requirement_group' => $group,
                'notes' => $notes,
            ];
        };

        $englishAny = fn (
            int $homeLanguageMark,
            int $firstAdditionalLanguageMark,
            string $group,
            ?string $notes = null,
        ): array => [
            $req('English Home Language', $homeLanguageMark, 'any_of', $group, $notes),
            $req('English First Additional Language', $firstAdditionalLanguageMark, 'any_of', $group, $notes),
        ];

        $closingDate = '2026-09-30';
        $closingDateLabel = '30 September 2026';

        $bursaries = [
            $entry(
                $company(
                    'A2A Kopano Incorporated',
                    null,
                    'A South African auditing and advisory firm formed in 2005, serving private and public sector clients.',
                    'marcelenej@cbarnes.co.za',
                    '012 460 9885',
                ),
                $bursary([
                    'title' => 'A2A Kopano Inc. Bursary',
                    'category' => 'Accounting',
                    'summary' => 'Bursary support for students pursuing Chartered Accountancy studies.',
                    'fields_covered' => 'Chartered Accountancy field.',
                    'coverage_value' => 'R25 000 to R40 000 per student per year.',
                    'service_contract' => 'Graduates must undertake employment at an A2A Kopano Incorporated office in the Eastern Cape for a period equal to the bursary awarded.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Studying towards a Chartered Accountant (SA) qualification',
                        'Achieved high academic results',
                        'Preference for students who completed first year and students residing in the Eastern Cape',
                    ],
                    'application_method' => 'Apply by email to marcelenej@cbarnes.co.za or post to The Bursary Officer, PO Box 137, Queenstown, 5320.',
                    'supporting_documents' => [
                        'Covering letter',
                        'Certified copy of ID document',
                        'Certified copy of Matric certificate',
                        'Full academic record or transcript on tertiary institution letterhead',
                        'Curriculum Vitae',
                    ],
                    'closing_date' => null,
                    'closing_date_label' => '30 September annually',
                    'contact_name' => 'The Bursary Officer',
                    'contact_email' => 'marcelenej@cbarnes.co.za',
                    'contact_phone' => '012 460 9885',
                    'source_url' => 'https://www.zabursaries.co.za/accounting-bursaries-south-africa/a2a-kopano-inc-bursary/',
                    'apply_url' => 'mailto:marcelenej@cbarnes.co.za',
                ]),
            ),
            $entry(
                $company(
                    'East London Industrial Development Zone',
                    'https://www.elidz.co.za/',
                    'A public entity that develops and operates a specialised industrial complex in the Eastern Cape.',
                    'events@elidz.co.za',
                    null,
                ),
                $bursary([
                    'title' => 'East London Industrial Development Zone (ELIDZ) Bursary',
                    'category' => 'Science',
                    'summary' => 'Bursary for Eastern Cape students pursuing undergraduate Mathematics, Science and Technology related fields.',
                    'fields_covered' => 'Undergraduate studies within Mathematics, Science and Technology and related fields.',
                    'coverage_value' => 'Up to R50 000 for registration fees, tuition fees, prescribed books, approved study materials, accommodation and meals in a university-administered residence.',
                    'service_contract' => 'Recipients must fulfil a service-binding contract and complete vacation work at IDZ during mid-year or end-of-year holidays for the duration of the bursary.',
                    'renewal' => 'Awarded for one academic year at a time and renewable based on maintaining a minimum average of 60% for final exams.',
                    'eligibility_requirements' => [
                        'South African citizen or naturalized South African citizen',
                        'Between 16 and 25 years old',
                        'Reside within the Eastern Cape province in a township or village',
                        'Completed Matric',
                        'Minimum 60% for Mathematics, not Mathematical Literacy',
                        'Minimum 60% for all other Matric subjects',
                        'Studying or intending to study full-time towards an undergraduate qualification in one of the listed fields in 2026',
                        'Accepted or provisionally accepted at a recognised and accredited South African university',
                        'Intend to pursue postgraduate studies after undergraduate studies',
                        'From a disadvantaged background and in need of financial assistance',
                        'Not receiving any other bursary funding',
                        'Not under obligation to another bursary provider',
                    ],
                    'application_method' => 'Applications must be submitted online via the ELIDZ Bursary Application portal.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Certified copy of Matric certificate',
                        'Most recent academic record or transcript, if currently studying',
                        'Proof of university acceptance or provisional acceptance',
                        'Parents or guardians proof of residence',
                        'Parents or guardians proof of income',
                        'Motivational letter',
                        'Achievements or merit certificates, if applicable',
                        'Testimonial letter from a prominent community member',
                        'Testimonial letter from school Principal, lecturer, or university staff',
                    ],
                    'closing_date' => '2026-01-30',
                    'closing_date_label' => '30 January 2026',
                    'contact_name' => 'Nosiphiwo Nontshinga',
                    'contact_email' => 'events@elidz.co.za',
                    'source_url' => 'https://www.zabursaries.co.za/science-bursaries-south-africa/east-london-idz-bursary/',
                    'apply_url' => 'https://elidz-portal-b2c.powerappsportals.com/',
                ]),
                [
                    $req('Mathematics', 60, 'required', null, 'Mathematics, not Mathematical Literacy.'),
                    $req('All other Matric subjects', 60, 'all_other_subjects', null, 'The source states that applicants must have achieved 60% for all other Matric subjects.'),
                ],
            ),
            $entry(
                $company(
                    'Amandla Omoya Trust',
                    null,
                    'A community trust supporting public benefit activities around the Jeffreys Bay Wind Farm area.',
                    'apply@StudyTrust.org.za',
                    '011 482 1501 / 011 403 1632',
                ),
                $bursary([
                    'title' => 'Amandla Omoya Trust Bursary',
                    'category' => 'General',
                    'summary' => 'Community bursary for students living within 50km of the Jeffreys Bay Wind Farm.',
                    'fields_covered' => 'Any field of study, including NQF level 6 technical and vocational programmes, National Diplomas and degree programmes.',
                    'coverage_value' => 'Registration fees, tuition fees, examination fees, study materials, accommodation and meals. Value is determined individually.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Resides within 50km of the Jeffreys Bay Wind Farm in the surrounding community',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study towards an eligible qualification in any field',
                        'Accepted at a recognised public or private tertiary education or training institution in South Africa',
                        'Demonstrates financial need',
                    ],
                    'application_method' => 'Apply online through the StudyTrust Amandla Omoya Trust bursary application.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Certified copy of latest Matric results or certificate',
                        'Certified copy of latest academic results, if currently studying',
                        'Proof of acceptance to an institution',
                        'Proof of residential address',
                        'Certified proof of parents or guardians household income',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'StudyTrust',
                    'contact_email' => 'apply@StudyTrust.org.za',
                    'contact_phone' => '011 482 1501 / 011 403 1632',
                    'source_url' => 'https://www.zabursaries.co.za/general-bursaries-south-africa/amandla-omoya-trust-bursary/',
                    'apply_url' => 'https://studytrust.org.za/amandla-omoya-trust-bursary-programme',
                ]),
            ),
            $entry(
                $company(
                    'Amazon Web Services',
                    'https://aws.amazon.com/',
                    'Amazon Web Services provides cloud computing platforms and services.',
                    'apply@StudyTrust.org.za',
                    '011 403 1632',
                ),
                $bursary([
                    'title' => 'AWS Skills Development Bursary',
                    'category' => 'Engineering',
                    'summary' => 'Full-cost bursary for technology, engineering, commerce and education fields relevant to the technology sector.',
                    'fields_covered' => 'Computer Science, Computer Engineering, Information Technology, Accounting and Finance, Engineering, and BEd Maths and Science. Students with disabilities may apply for any undergraduate or postgraduate programme.',
                    'coverage_value' => 'Tuition fees, stationery, books, personal computer, accommodation and subsistence up to capped amounts.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Currently in Matric or completed Matric',
                        'Studying or intending to study full-time in an eligible undergraduate or postgraduate qualification in 2027',
                        'Studying or intending to study at a recognised and accredited South African university',
                        'Strong academic record and leadership potential',
                        'Preference for students living with disabilities',
                    ],
                    'application_method' => 'Apply online through the StudyTrust AWS Skills Development bursary application.',
                    'supporting_documents' => [
                        'Clear head and shoulders photograph',
                        'Certified copy of South African ID document',
                        'Grade 11 final results and Matric June results, if currently in Matric',
                        'Matric certificate, if completed Matric',
                        'Full academic record and latest available results',
                        'Proof of parents or guardians household income',
                        'Parents death certificates or divorce or child support documents, if applicable',
                        'Proof of disability, if applicable',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'StudyTrust',
                    'contact_email' => 'apply@StudyTrust.org.za',
                    'contact_phone' => '011 403 1632 / 087 511 3373',
                    'source_url' => 'https://www.zabursaries.co.za/engineering-bursaries-south-africa/aws-skills-development-bursary/',
                    'apply_url' => 'https://studytrust.org.za/amazon-web/',
                ]),
                [
                    $req('Mathematics', 65),
                    $req('Physical Sciences', 65),
                    ...$englishAny(65, 65, 'AWS English requirement', 'English Home Language or English First Additional Language is accepted.'),
                ],
            ),
            $entry(
                $company(
                    'Cisco Charitable Foundation Trust South Africa',
                    'https://www.cisco.com/',
                    'A Cisco-linked charitable trust supporting IT education opportunities for South African students.',
                    'apply@StudyTrust.org.za',
                    '011 403 1632',
                ),
                $bursary([
                    'title' => 'Cisco Charitable Foundation Trust Bursary',
                    'category' => 'Computer Science and IT',
                    'summary' => 'Bursary for NQF level 7 or 8 studies in computer and software-related fields.',
                    'fields_covered' => 'Computer Engineering, Computer Science, Information Technology and Software Engineering.',
                    'coverage_value' => 'See provider for the confirmed funding package.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Completed Matric or currently in Matric',
                        'Studying or intending to study in one of the listed fields',
                        'Entering 1st to 4th year of study in 2027, including BTech NQF 7 or Honours NQF 8',
                        'Accepted or registered at a private or public institution registered with the Department of Education in South Africa',
                        'Strong academic record',
                        'Proven financial need, with combined family income between R350 000 and R600 000 per year',
                        'Preference for equity candidates',
                    ],
                    'application_method' => 'Apply online through the StudyTrust Cisco Charitable Foundation Trust bursary application.',
                    'supporting_documents' => [
                        'Clear head and shoulders photograph',
                        'Matric certificate or latest Matric results',
                        'Full academic record, if currently studying',
                        'Proof of acceptance or registration at a tertiary institution',
                        'Proof of parents or guardians household income',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'StudyTrust',
                    'contact_email' => 'apply@StudyTrust.org.za',
                    'contact_phone' => '011 403 1632',
                    'source_url' => 'https://www.zabursaries.co.za/computer-science-it-bursaries-south-africa/cisco-charitable-foundation-trust-bursary/',
                    'apply_url' => 'https://studytrust.org.za/cisco/',
                ]),
            ),
            $entry(
                $company(
                    'Department of Land Reform and Rural Development',
                    'https://www.dlrrd.gov.za/',
                    'South African government department responsible for land reform, rural development and land administration.',
                    'Externalbursaries@dlrrd.gov.za',
                    '012 312 8352 / 012 312 8337',
                ),
                $bursary([
                    'title' => 'Department of Land Reform and Rural Development (DLRRD) Bursary',
                    'category' => 'Government',
                    'summary' => 'Government bursary for Geomatics, GIS, Land Surveying and Town or Urban and Regional Planning studies.',
                    'fields_covered' => 'Geo-informatics, Geographic Information Science, Geomatics, Surveying, GIS, Land Surveying, Town Planning, Urban and Regional Planning, and postgraduate Geomatics or Planning studies.',
                    'coverage_value' => 'Tuition, accommodation, books, meals and living allowance.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'From a previously disadvantaged background or rural community',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study full-time in one of the listed fields',
                        'Studying or intending to study at a recognised and accredited South African university',
                        'Meets the Matric subject levels for the selected DLRRD study route',
                        'Not a staff member of the department',
                    ],
                    'application_method' => 'Apply online through the DLRRD Microsoft Forms application or submit the downloaded form by email to Externalbursaries@dlrrd.gov.za.',
                    'supporting_documents' => [
                        'Certified copy of ID document, not older than 3 months',
                        'Certified copies of parents or guardians ID documents',
                        'Grade 11 final results and latest Matric results, if currently in Matric',
                        'Certified copy of Matric certificate, if completed Matric',
                        'Certified recent academic transcripts, if currently studying',
                        'Proof of university registration or acceptance',
                        'Proof of address',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'DLRRD external bursaries',
                    'contact_email' => 'Externalbursaries@dlrrd.gov.za',
                    'contact_phone' => '060 972 8820 / 082 827 6245',
                    'source_url' => 'https://www.zabursaries.co.za/government-bursaries-south-africa/department-of-land-reform-and-rural-development-dlrrd-bursary/',
                    'apply_url' => 'https://forms.office.com/pages/responsepage.aspx?id=NSp5H6cCPk6eev9ArjkMtuaX2A0iefdNvcrkuGSUQWNUOEZLQldEWklIMUZUV1E1N0xGSkpBUUszTy4u&origin=QRCode&route=shorturl',
                ]),
                [
                    $req('Mathematics', 60, 'option_required', 'BSc route', 'BSc applicants need level 5 for Mathematics.'),
                    $req('Physical Sciences', 60, 'option_any_of', 'BSc route', 'BSc applicants need level 5 for Physical Science or Geography.'),
                    $req('Geography', 60, 'option_any_of', 'BSc route', 'BSc applicants need level 5 for Physical Science or Geography.'),
                    $req('Mathematics', 50, 'option_required', 'Bachelors or diploma route', 'Bachelor degree and diploma applicants need level 4 for Mathematics.'),
                    $req('Physical Sciences', 50, 'option_required', 'Bachelors or diploma route', 'Bachelor degree and diploma applicants need level 4 for Physical Science.'),
                ],
            ),
            $entry(
                $company(
                    'Enel Green Power South Africa',
                    'https://www.enelgreenpower.com/countries/africa/south-africa',
                    'A renewable energy company operating wind and solar projects in South Africa.',
                    'apply@StudyTrust.org.za',
                    '011 403 1632',
                ),
                $bursary([
                    'title' => 'Enel Green Power Bursary',
                    'category' => 'General',
                    'summary' => 'Bursary for students living within 50km of selected Enel Green Power operations.',
                    'fields_covered' => 'Any field, including TVET programmes, National Diplomas and degree programmes.',
                    'coverage_value' => 'May cover tuition, registration, examination fees, accommodation, meals and learning materials. Value is determined individually.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Resides within 50km of an Enel site',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study towards a Diploma, Degree or NQF level 4 technical and vocational programme',
                        'Studying or intending to study at a recognised and accredited public institution in South Africa',
                        'Strong academic record',
                        'Proven financial need',
                    ],
                    'application_method' => 'Apply online through the StudyTrust Enel Green Power bursary application.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Matric certificate or most recent results',
                        'Proof of tertiary acceptance',
                        'Proof of residence',
                        'Proof of parents or guardians household income',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'StudyTrust',
                    'contact_email' => 'b.ndlovu@StudyTrust.org.za / apply@StudyTrust.org.za',
                    'contact_phone' => '011 403 1632 x 200',
                    'source_url' => 'https://www.zabursaries.co.za/general-bursaries-south-africa/enel-bursary/',
                    'apply_url' => 'https://studytrust.org.za/enel-green-power-rsa-bursaries/',
                ]),
            ),
            $entry(
                $company(
                    'Industrial Development Corporation',
                    'https://www.idc.co.za/',
                    'A South African development finance institution supporting industrial development and economic growth.',
                    'bursary@idc.co.za',
                    '011 269 3374',
                ),
                $bursary([
                    'title' => 'Industrial Development Corporation (IDC) Bursary',
                    'category' => 'Commerce',
                    'summary' => 'Bursary for finance, management, STEM, law and selected postgraduate Honours studies.',
                    'fields_covered' => 'Finance and Management, STEM, Law, and selected Honours fields including Accounting CTA, Actuarial Science, Law, Mathematics and Statistics.',
                    'coverage_value' => 'Full tuition fees, accommodation, meal allowance, transport allowance and a once-off laptop.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Unemployed and not older than 26 years',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study full-time towards a first undergraduate qualification in an eligible field',
                        'Postgraduate funding limited to Law, Accounting CA, Actuarial Science, Mathematics and Statistics',
                        'Studying or intending to study at a recognised public University or University of Technology in South Africa',
                        'Matric students need the listed IDC academic threshold; tertiary students need the listed tertiary threshold',
                        'Combined household income not more than R350 000 per year, with missing-middle applicants also considered',
                        'Preference for students with disabilities and students from Quintile 1 to 3 or rural schools',
                    ],
                    'application_method' => 'Apply online through the IDC bursary portal.',
                    'supporting_documents' => [
                        'Certified copy of ID document, not older than 3 months',
                        'Grade 11 final results and Matric June results, if currently in Matric',
                        'Certified copy of Matric certificate, if completed Matric',
                        'Latest academic results',
                        'Proof of acceptance or provisional admission',
                        'Certified copies of parents or guardians ID documents',
                        'Proof of parents or guardians income and related family documents, if applicable',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'IDC bursaries',
                    'contact_email' => 'bursary@idc.co.za',
                    'contact_phone' => '011 269 3374',
                    'source_url' => 'https://www.zabursaries.co.za/commerce-bursaries-south-africa/industrial-development-corporation-idc-bursary/',
                    'apply_url' => 'https://protected.idc.co.za/BursaryPortal/',
                ]),
            ),
            $entry(
                $company(
                    'Investec',
                    'https://www.investec.com/',
                    'A specialist bank and wealth manager operating in South Africa and internationally.',
                    'apply@StudyTrust.org.za',
                    '011 403 1632',
                ),
                $bursary([
                    'title' => 'Investec CSI Bursary',
                    'category' => 'Commerce',
                    'summary' => 'Full-cover bursary for undergraduate studies relevant to the financial services sector.',
                    'fields_covered' => 'Actuarial Science, Business Science, Commerce, Commercial LLB, Computer Science, Engineering, Informatics, Information Science, Information Technology, Mathematics, Medicine and Science.',
                    'coverage_value' => 'Full cover for study-related expenses.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Completed Matric or currently in Matric',
                        'Intending to study or in first year of full-time undergraduate study in an eligible field',
                        'Studying or intending to study at a recognised and accredited public South African university',
                        'Meets the listed Mathematics, English and other-subject thresholds',
                        'First-year university applicants need at least 60% overall for first semester exams',
                        'Actuarial Science applicants must be in first year, unless studying Business Science at UCT',
                    ],
                    'application_method' => 'Apply online through the StudyTrust Investec bursary application.',
                    'supporting_documents' => [
                        'Certified copy of South African ID document',
                        '2026 mid-year results, progress report or latest results',
                        'Matric certificate, if completed Matric',
                        'Proof of parents or guardians household income',
                        'Parents death certificates, divorce certificate or separation statement, if applicable',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'StudyTrust',
                    'contact_email' => 'apply@StudyTrust.org.za',
                    'contact_phone' => '011 403 1632',
                    'source_url' => 'https://www.zabursaries.co.za/commerce-bursaries-south-africa/investec-bursary/',
                    'apply_url' => 'https://studytrust.org.za/investec-bursary-programme/',
                ]),
                [
                    $req('Mathematics', 70, 'required', null, 'Mathematics, not Mathematical Literacy.'),
                    ...$englishAny(65, 70, 'Investec English requirement', 'English Home Language 65% or English First Additional Language 70%.'),
                    $req('All other Matric subjects', 60, 'all_other_subjects', null, 'Applies to all other Matric subjects.'),
                ],
            ),
            $entry(
                $company(
                    'Investec',
                    'https://www.investec.com/',
                    'A specialist bank and wealth manager operating in South Africa and internationally.',
                    'CSIHighSchoolBursary@investec.co.za',
                    null,
                ),
                $bursary([
                    'title' => 'Investec High School Bursary',
                    'category' => 'High School',
                    'summary' => 'High school bursary for students entering Grades 10 to 12, aimed mainly at township and rural school learners.',
                    'fields_covered' => 'High school funding for learners with strong academic potential, especially in Mathematics and Physical Science.',
                    'coverage_value' => 'Funding for the remainder of the recipients high school studies.',
                    'renewal' => 'Students are funded for the remainder of their high school studies, subject to selection and programme conditions.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Entering Grade 10, Grade 11 or Grade 12 in 2027',
                        'Strong academic record',
                        'Studies Pure Mathematics, Physical Science, Accounting and English from Grade 10 to Grade 12',
                        'Meets the listed 70% academic thresholds',
                        'Proven financial need',
                        'Enrolled at current school for at least one year',
                        'School meets the listed pass-rate, university-entrance and subject-performance criteria',
                    ],
                    'application_method' => 'Apply online through the StudyTrust Investec High School bursary application.',
                    'supporting_documents' => [
                        'Certified copy of ID document or birth certificate',
                        'June 2025 and final results',
                        'June 2026 Grade 9, 10 or 11 results',
                        'Certificates of achievements at school',
                        'Curriculum Vitae',
                        'Proof of parents or guardians household income and family-status documents, if applicable',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'Investec High School Bursary',
                    'contact_email' => 'CSIHighSchoolBursary@investec.co.za',
                    'source_url' => 'https://www.zabursaries.co.za/general-bursaries-south-africa/investec-high-school-bursary/',
                    'apply_url' => 'https://studytrust.org.za/investec-high-school-bursary/',
                ]),
                [
                    $req('Mathematics', 70, 'required', null, 'Mathematics, not Mathematical Literacy.'),
                    ...$englishAny(70, 70, 'Investec High School English requirement'),
                    $req('All other subjects', 70, 'all_other_subjects', null, 'The source lists 70% for all other subjects.'),
                ],
            ),
            $entry(
                $company(
                    'Old Mutual Imfundo Trust',
                    'https://www.oldmutual.co.za/',
                    'A scholarship initiative established by Old Mutual Investment Group to support tertiary study.',
                    'apply@StudyTrust.org.za',
                    '011 403 1632',
                ),
                $bursary([
                    'title' => 'Old Mutual Imfundo Trust Scholarship',
                    'category' => 'Commerce',
                    'summary' => 'Scholarship for undergraduate business, commerce, technology, engineering, finance and management studies, plus postgraduate Climate Studies.',
                    'fields_covered' => 'Business, Commerce, Computer Science and related qualifications, Data Science, Engineering, Finance, Management Sciences or Studies, and postgraduate Climate Studies.',
                    'coverage_value' => 'See provider for the confirmed scholarship package.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study full-time towards an eligible qualification',
                        'Entering 1st or 2nd year of study in 2027, except Climate Studies which is postgraduate only',
                        'Studying or intending to study at a recognised and accredited tertiary institution in South Africa',
                        'Matric applicants meet the listed overall, Mathematics and English thresholds',
                        'Current students have at least 65% overall in most recent exams',
                        'Preference for rural and township backgrounds',
                    ],
                    'application_method' => 'Apply online through the StudyTrust Old Mutual Imfundo Trust scholarship application.',
                    'supporting_documents' => [
                        'Clear head and shoulders photograph',
                        'Certified copy of South African ID document',
                        'Grade 11 final results and Matric June results, if currently in Matric',
                        'Matric certificate, if completed Matric',
                        'Full academic record and latest available results',
                        'Proof of parents or guardians household income',
                        'Parents death certificates or child support documents, if applicable',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'StudyTrust',
                    'contact_email' => 'apply@StudyTrust.org.za',
                    'contact_phone' => '011 403 1632',
                    'source_url' => 'https://www.zabursaries.co.za/commerce-bursaries-south-africa/old-mutual-imfundo-trust-scholarship/',
                    'apply_url' => 'https://studytrust.org.za/old-mutual/',
                ]),
                [
                    $req('Overall average', 70, 'minimum_average', null, 'Current Matric applicants need 70% overall in mid-year Matric exams.'),
                    $req('Mathematics', 70),
                    ...$englishAny(60, 70, 'Old Mutual Imfundo English requirement', 'English Home Language 60% or English First Additional Language 70%.'),
                ],
            ),
            $entry(
                $company(
                    'Royal Bafokeng Institute',
                    'https://www.bafokenginstitute.org.za/',
                    'An institute of the Royal Bafokeng Nation providing education and training programmes.',
                    'rbienquiries@bafokeng.com',
                    '014 566 1400',
                ),
                $bursary([
                    'title' => 'Royal Bafokeng Institute (RBI) Student Loan',
                    'category' => 'Student Loan',
                    'summary' => 'Student loan for Royal Bafokeng residents pursuing selected undergraduate fields at North West or Gauteng universities.',
                    'fields_covered' => 'Accounting and Auditing, Education, Engineering, Fine Arts, Health Sciences, Law and Social Work.',
                    'coverage_value' => 'Student loan support. See provider for confirmed loan value and terms.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Bona fide Royal Bafokeng resident',
                        'Intending to study towards an undergraduate qualification in one of the listed fields',
                        'Accepted at a public and accredited university in North West or Gauteng',
                        'Proven financial need',
                        'Minimum APS score of 30 excluding Life Orientation',
                        'Applied for NSFAS funding',
                    ],
                    'application_method' => 'Download the application form or collect a copy from the RBI campus, then submit the completed form and documents to Sun City Road (R565), Salema, Phokeng 0335.',
                    'supporting_documents' => [
                        'Certified copy of ID document, not older than 3 months',
                        'Grade 11 final results and latest Matric results, if currently in Matric',
                        'Matric final results or certificate, if completed Matric',
                        'Academic transcript, if currently studying',
                        'Proof of parents or guardians household income',
                        'Certified copies of parents or guardians ID documents',
                        'Proof of NSFAS application',
                        'Proof of university acceptance',
                        'Recommendation letter from Kgosana',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'Royal Bafokeng Institute',
                    'contact_email' => 'rbienquiries@bafokeng.com',
                    'contact_phone' => '014 566 1400',
                    'source_url' => 'https://www.zabursaries.co.za/construction-and-built-environment-bursaries-south-africa/royal-bafokeng-institute-bursary/',
                    'apply_url' => 'https://www.bafokenginstitute.org.za/wp-content/uploads/2026/03/Student-Loan-Form-2027-PDF.docx.pdf',
                ]),
                [
                    $req('APS excluding Life Orientation', null, 'minimum_aps', null, 'Minimum APS score of 30, excluding Life Orientation.', 30),
                ],
            ),
            $entry(
                $company(
                    'Sage South Africa',
                    'https://www.sage.com/en-za/',
                    'A provider of accounting, payroll, payment and business management software.',
                    'apply@StudyTrust.org.za',
                    '011 403 1632',
                ),
                $bursary([
                    'title' => 'Sage Bursary',
                    'category' => 'Computer Science and IT',
                    'summary' => 'Bursary for undergraduate Accounting, Finance, Computer Engineering, Computer Science and Information Technology studies.',
                    'fields_covered' => 'Accounting and Finance, Computer Engineering, Computer Science and Information Technology. Students with disabilities may apply for any undergraduate or postgraduate programme.',
                    'coverage_value' => 'Tuition fees, stationery, books, accommodation, current fees and outstanding student debt up to capped amounts.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Previously disadvantaged individual',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study towards an eligible undergraduate qualification in 2027',
                        'Studying or accepted to study at a recognised and accredited public tertiary institution in South Africa',
                        'Current Matric students meet the listed Mathematics and Physical Science thresholds',
                        'Current university students have consistently achieved at least 65% overall',
                        'Household income between R350 000 and R500 000 per year, or NSFAS application conditions are met',
                        'Preference for students with disabilities',
                    ],
                    'application_method' => 'Apply online through the StudyTrust Sage bursary application.',
                    'supporting_documents' => [
                        'Clear head and shoulders photograph',
                        'Certified copy of South African ID document',
                        'Grade 11 final results and Matric June results, if currently in Matric',
                        'Matric certificate, if completed Matric',
                        'Full academic record and latest available results',
                        'Proof of parents or guardians household income',
                        'Parents death certificates or child support documents, if applicable',
                        'Proof of disability, if applicable',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'StudyTrust',
                    'contact_email' => 'apply@StudyTrust.org.za',
                    'contact_phone' => '011 403 1632',
                    'source_url' => 'https://www.zabursaries.co.za/computer-science-it-bursaries-south-africa/sage-bursary/',
                    'apply_url' => 'https://studytrust.org.za/sage/',
                ]),
                [
                    $req('Mathematics', 75),
                    $req('Physical Sciences', 75),
                ],
            ),
            $entry(
                $company(
                    'Sappi',
                    'https://www.sappi.com/',
                    'A global pulp, paper and woodfibre company headquartered in Johannesburg.',
                    'youngtalent@sappi.com',
                    '011 407 8111',
                ),
                $bursary([
                    'title' => 'Sappi Bursary',
                    'category' => 'Engineering',
                    'summary' => 'Engineering and forestry bursary for undergraduate studies linked to Sappi business operations.',
                    'fields_covered' => 'Chemical Engineering, Civil Engineering, Electrical Engineering, Forestry and Wood Science, Industrial Engineering, Mechanical Engineering and Mechatronics Engineering.',
                    'coverage_value' => 'May cover tuition fees, prescribed textbooks, accommodation and a living allowance, depending on household income.',
                    'service_contract' => 'Recipients may complete vacation work during July and December holidays and may enter the Sappi Engineer-in-Training programme after successful completion.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Between 17 and 25 years old',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study full-time towards an eligible qualification in 2027',
                        'Studying or intending to study at a recognised and accredited South African university',
                        'Meets the listed Mathematics, Physical Science and English thresholds',
                        'Preference for students living near Sappi main business operations',
                    ],
                    'application_method' => 'Apply online through the Sappi careers bursary application.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Latest Matric results and Grade 11 final results, if currently in Matric',
                        'Certified copy of Matric certificate, if completed Matric',
                        'Full tertiary academic record, if currently at tertiary level',
                        'Curriculum Vitae',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'Sappi Young Talent',
                    'contact_email' => 'youngtalent@sappi.com',
                    'contact_phone' => '011 407 8111',
                    'source_url' => 'https://www.zabursaries.co.za/engineering-bursaries-south-africa/sappi-bursary/',
                    'apply_url' => 'https://sappi.csod.com/ux/ats/careersite/1/home/requisition/240?c=sappi',
                ]),
                [
                    $req('Mathematics', 70, 'required', null, 'Mathematics, not Mathematical Literacy.'),
                    $req('Physical Sciences', 70),
                    ...$englishAny(60, 60, 'Sappi English requirement'),
                ],
            ),
            $entry(
                $company(
                    'South African Reserve Bank',
                    'https://www.resbank.co.za/',
                    'South Africa central bank, responsible for price stability and financial-system functions.',
                    'info@ttibursaries.co.za',
                    '010 746 4366',
                ),
                $bursary([
                    'title' => 'SARB External Bursary',
                    'category' => 'Commerce',
                    'summary' => 'Undergraduate bursary for fields related to SARB functions and other scarce-skills fields.',
                    'fields_covered' => 'Accounting, Actuarial Science, Economics, Finance, Information Technology, Law, Mathematical Statistics, Dentistry, Medicine, Social Work and other scarce skills fields.',
                    'coverage_value' => 'See provider for the confirmed funding package.',
                    'renewal' => 'Reviewed annually. Students do not have to reapply each year.',
                    'service_contract' => 'Recipients must sign an agreement with SARB.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Under 30 years old',
                        'Completed Matric or currently in Matric',
                        'Intending to study full-time towards an undergraduate degree in an eligible field',
                        'Entering first year of study in 2027',
                        'Accepted or provisionally accepted at a recognised and accredited South African university',
                        'At least 70% overall for Matric June exams',
                        'Financial need and disadvantaged background',
                    ],
                    'application_method' => 'Apply online using promotional code SARBEXT27 or submit the downloaded form by email or post to TTI Bursaries.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Certified Matric June results, if currently in Matric',
                        'Certified Matric final results or certificate, if completed Matric',
                        'Proof of university acceptance or provisional acceptance for 2027',
                        'Motivational essay of approximately 250 words',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'TTI Bursaries',
                    'contact_email' => 'info@ttibursaries.co.za',
                    'contact_phone' => '010 746 4366',
                    'source_url' => 'https://www.zabursaries.co.za/commerce-bursaries-south-africa/south-african-reserve-bank-bursary/',
                    'apply_url' => 'https://sarb-bursary-manager.replit.app/',
                ]),
                [
                    $req('Overall average', 70, 'minimum_average', null, 'Current Matric applicants need at least 70% overall for Matric June exams.'),
                ],
            ),
            $entry(
                $company(
                    'South African Reserve Bank',
                    'https://www.resbank.co.za/',
                    'South Africa central bank, responsible for price stability and financial-system functions.',
                    'info@ttibursaries.co.za',
                    '010 746 4366',
                ),
                $bursary([
                    'title' => 'SARB Economics Bursary',
                    'category' => 'Commerce',
                    'summary' => 'Economics bursary from the SARB Economic Research Department and SARB Academy.',
                    'fields_covered' => 'Economics, Economics and Econometrics, Economics and Mathematical Statistics, and Economic Science.',
                    'coverage_value' => 'See provider for the confirmed funding package.',
                    'service_contract' => 'Recipients must sign an agreement with SARB.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Under 30 years old',
                        'Completed Matric or currently in Matric',
                        'Intending to study full-time towards an undergraduate Economics degree',
                        'Entering first year of study in 2027',
                        'Accepted or provisionally accepted at a recognised and accredited South African university',
                        'At least 70% overall for the 2026 academic year',
                        'At least 70% for English and Mathematics',
                        'Financial need and disadvantaged background',
                    ],
                    'application_method' => 'Apply online using promotional code SARBERD27 or submit the downloaded form by email or post to TTI Bursaries.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Certified Matric June results, if currently in Matric',
                        'Certified Matric final results or certificate, if completed Matric',
                        'Proof of university acceptance for 2027',
                        'Motivational essay of approximately 250 words',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'TTI Bursaries',
                    'contact_email' => 'info@ttibursaries.co.za',
                    'contact_phone' => '010 746 4366',
                    'source_url' => 'https://www.zabursaries.co.za/commerce-bursaries-south-africa/sarb-economics-bursary/',
                    'apply_url' => 'https://sarb-bursary-manager.replit.app/',
                ]),
                [
                    $req('Overall average', 70, 'minimum_average', null, 'Minimum overall average for the 2026 academic year.'),
                    $req('Mathematics', 70),
                    ...$englishAny(70, 70, 'SARB Economics English requirement'),
                ],
            ),
            $entry(
                $company(
                    'South African National Roads Agency SOC Limited',
                    'https://www.nra.co.za/',
                    'A state-owned entity responsible for South Africa national road network.',
                    null,
                    null,
                ),
                $bursary([
                    'title' => 'SANRAL Bursary',
                    'category' => 'Engineering',
                    'summary' => 'Bursary for undergraduate fields critical to SANRAL operations.',
                    'fields_covered' => 'Civil Engineering, Computer Science or Information Systems, Human Resources Management, and Public Procurement or Supply Chain Management.',
                    'coverage_value' => 'Full bursaries cover registration, tuition, study material and equipment, accommodation, meals, living allowance and wellness plan access. Partial bursaries cover registration, tuition, accommodation and wellness plan access.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Under 35 years old',
                        'Currently in Matric or has completed Matric',
                        'Entering first year of undergraduate study in 2027',
                        'Studying or accepted to study full-time in an eligible field',
                        'Studying or accepted at a recognised and accredited public South African tertiary institution',
                        'Meets academic requirements for selected qualification',
                        'Matric students need at least 70% overall',
                        'Proven financial need',
                        'Not receiving other bursary funding',
                        'Students with disabilities are welcome to apply',
                    ],
                    'application_method' => 'Apply online through the SANRAL bursary application.',
                    'supporting_documents' => [
                        'Certified copy of ID document or birth certificate',
                        'Current Matric students: certified term 1 and 2 results',
                        'Certified proof of tertiary registration',
                        'One-page motivational letter',
                        'Certified copies of parents or guardians ID documents',
                        'Certified proof of parents or guardians income',
                        'Parents or guardians proof of residence',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'SANRAL bursaries',
                    'contact_email' => null,
                    'source_url' => 'https://www.zabursaries.co.za/engineering-bursaries-south-africa/sanral-bursary/',
                    'apply_url' => 'https://www.nra.co.za/Bursaries',
                ]),
                [
                    $req('Overall average', 70, 'minimum_average', null, 'Matric students need a minimum overall average of 70%.'),
                ],
            ),
            $entry(
                $company(
                    'South African Actuaries Development Programme',
                    'https://www.saadp.co.za/',
                    'An independent non-profit programme supporting transformation in the actuarial profession.',
                    'myapplication@saadp.co.za',
                    '011 642 2202',
                ),
                $bursary([
                    'title' => 'South African Actuaries Development Programme (SAADP) Bursary',
                    'category' => 'Science',
                    'summary' => 'Actuarial Science bursary for study at SAADP partner universities.',
                    'fields_covered' => 'Actuarial Science and related qualifications at UCT, University of Pretoria or Wits.',
                    'coverage_value' => 'Tuition fees, on-campus or approved accommodation, meal allowance, textbooks, study materials, tutorials, mentoring, psychosocial support and work-readiness support.',
                    'renewal' => 'Renewable each year based on academic performance and availability of funds.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Currently in Matric entering first year in 2027 or in 1st, 2nd, 3rd or Honours level of study',
                        'Studying or intending to study towards an Actuarial Science qualification',
                        'Studying or intending to study at UCT, University of Pretoria or Wits',
                        'Non-partner university students must have applied and been accepted at a partner university',
                        'Minimum 80% for Mathematics and English in Matric',
                        'Physical Science may be required by some universities',
                        'Strong and consistent academic performance',
                        'Proven financial need',
                    ],
                    'application_method' => 'Apply online through the SAADP bursary application portal.',
                    'supporting_documents' => [
                        'Certified copy of ID document or ID card',
                        'Grade 11 final results and Matric June results, if currently in Matric',
                        'Academic transcript, if currently at university',
                        'Matric final statement of results or NSC certificate when available',
                        'Acceptance or provisional admission letter to a partner university',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'SAADP',
                    'contact_email' => 'myapplication@saadp.co.za',
                    'contact_phone' => '011 642 2202',
                    'source_url' => 'https://www.zabursaries.co.za/science-bursaries-south-africa/south-african-actuaries-development-programme-bursary/',
                    'apply_url' => 'https://applynow.saadp.co.za/',
                ]),
                [
                    $req('Mathematics', 80, 'required', null, 'Mathematics, not Mathematical Literacy.'),
                    ...$englishAny(80, 80, 'SAADP English requirement'),
                    $req('Physical Sciences', 80, 'optional', null, 'Physical Science may be required by some universities.'),
                ],
            ),
            $entry(
                $company(
                    'Western Cape Department of Health and Wellness',
                    'https://www.westerncape.gov.za/dept/health',
                    'Western Cape provincial department responsible for public healthcare and health services.',
                    'Monray.Strydom@westerncape.gov.za',
                    '021 483 6610',
                ),
                $bursary([
                    'title' => 'Western Cape Department of Health and Wellness Bursary',
                    'category' => 'Medical',
                    'summary' => 'Bursary for Western Cape residents studying selected Health Science qualifications.',
                    'fields_covered' => 'Emergency Care, Emergency Medical Care, Medicine, Nursing, Occupational Therapy, Pharmacy, Physiotherapy and Speech Therapy.',
                    'coverage_value' => 'Registration fees, tuition fees and examination fees. Accommodation is not covered.',
                    'service_contract' => 'Recipients must sign a bursary contract and work back their obligation with government after graduation, with community service counting where applicable.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Resides in the Western Cape province',
                        'Unemployed',
                        'Completed Matric',
                        'Studying or intending to study full-time towards one of the listed Health Science qualifications',
                        'Studying, accepted or awaiting acceptance at a relevant accredited Higher Education Institution',
                        'Committed to studies and willing to complete clinical hours where required',
                        'No criminal record',
                    ],
                    'application_method' => 'Register, log in and apply through the Western Cape Department of Health and Wellness bursary platform.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Certified copy of Matric certificate',
                        'Certified most recent qualification or academic results',
                        'Certified proof of residence',
                        'Certified proof of parents or guardians income',
                        'Certified proof of disability, if applicable',
                        'Motivational letter',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'Western Cape Department of Health and Wellness bursaries',
                    'contact_email' => 'Monray.Strydom@westerncape.gov.za / Sisipho.Folose@westerncape.gov.za / Nathan.Kantwe@westerncape.gov.za',
                    'contact_phone' => '021 483 6610 / 021 483 6597 / 021 483 7038',
                    'source_url' => 'https://www.zabursaries.co.za/government-bursaries-south-africa/western-cape-department-of-health/',
                    'apply_url' => 'https://hsdims.westerncape.gov.za/healp_apex/f?p=107:3::::::',
                ]),
            ),
            $entry(
                $company(
                    'Tomorrow Trust',
                    'https://www.tomorrow.org.za/',
                    'A South African non-profit organisation supporting orphaned and vulnerable children through education and life skills.',
                    'info@tomorrow.org.za',
                    null,
                ),
                $bursary([
                    'title' => 'Tomorrow Trust Bursary',
                    'category' => 'Science',
                    'summary' => 'Undergraduate bursary for STEM-related studies with wraparound student support.',
                    'fields_covered' => 'BSc Sciences, Engineering, Information Technology, Computer Sciences, Property Sciences and STEM-related fields.',
                    'coverage_value' => 'Tuition fees, textbooks, equipment, accommodation, living allowances, mentorship, coaching, psychosocial support, masterclasses, career networking and future-ready skills support.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Between 18 and 35 years old',
                        'Currently in Matric or has completed Matric',
                        'Studying or intending to study full-time towards an undergraduate degree in an eligible field',
                        'Studying or intending to study at a recognised public university in South Africa',
                    ],
                    'application_method' => 'Apply online through the Tomorrow Trust Bursio application.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Latest Matric results, if currently in Matric',
                        'Matric certificate, if completed Matric',
                        'Full academic record, if currently studying',
                        'Proof of university registration or acceptance',
                        'Motivation letter',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'Tomorrow Trust',
                    'contact_email' => 'info@tomorrow.org.za / info@tomorrowtrust.org.za',
                    'source_url' => 'https://www.zabursaries.co.za/general-bursaries-south-africa/tomorrow-trust-sa-bursary/',
                    'apply_url' => 'https://bursio.co.za/bursary/80d45261-af68-480e-8ef4-397d46ebf3b3',
                ]),
            ),
            $entry(
                $company(
                    'South African National Space Agency',
                    'https://www.sansa.org.za/',
                    'A public entity focused on space science, engineering, remote sensing and space-sector development.',
                    'grants@sansa.org.za',
                    null,
                ),
                $bursary([
                    'title' => 'South African National Space Agency (SANSA) Bursary',
                    'category' => 'Science',
                    'summary' => 'Postgraduate bursary for Honours, Masters and Doctoral STEM studies linked to the space sector.',
                    'fields_covered' => 'Applied Mathematics, Remote Sensing, GIS, Computer and Electronic Engineering, Computer Science, Environmental and Geographical Science, Geoinformatics, Information Systems, Mathematics, Mechanical Engineering, Mechatronics, Physics, Space Science and related STEM fields.',
                    'coverage_value' => 'Honours funding of R150 000 per year, Masters funding of R160 000 per year and Doctoral funding of R170 000 per year.',
                    'eligibility_requirements' => [
                        '32 years old or younger',
                        'Studying or intending to study towards a postgraduate STEM qualification',
                        'Minimum 65% overall in last year of studies or last examination',
                        'Strong academic potential',
                        'Proven financial need',
                        'Interested in working in the space sector',
                    ],
                    'application_method' => 'Apply online through the SANSA bursary application.',
                    'supporting_documents' => [
                        'Certified copy of ID document in PDF format',
                        'Full university academic record from first year, including final year or midyear 2026 results',
                        'Official undergraduate university student account statement or NSFAS funding letter',
                        'SANSA testimonial by education official for Masters and Doctoral students',
                        'Draft proposal for Masters or Doctoral applicants',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'SANSA grants',
                    'contact_email' => 'grants@sansa.org.za',
                    'source_url' => 'https://www.zabursaries.co.za/engineering-bursaries-south-africa/sansa-bursary/',
                    'apply_url' => 'https://www.sansa.org.za/bursaries/application/',
                ]),
            ),
            $entry(
                $company(
                    'Department of Water and Sanitation',
                    'https://www.dws.gov.za/',
                    'South African government department responsible for water resources, water supply and sanitation policy.',
                    'bursaries@dws.gov.za',
                    '012 336 7149',
                ),
                $bursary([
                    'title' => 'Department of Water and Sanitation (DWS) Bursary',
                    'category' => 'Government',
                    'summary' => 'Government bursary for undergraduate and Honours studies in water and sanitation fields.',
                    'fields_covered' => 'Civil Engineering, Construction Management, Electrical Engineering, Environmental and Water Sciences, Geohydrology, Hydrology, Mechanical Engineering, Quantity Surveying and selected Honours fields.',
                    'coverage_value' => 'Registration fees, tuition fees, book allowance, stationery allowance, accommodation, food and monthly stipend.',
                    'service_contract' => 'On completion, recipients must join the Water Learning Academy for up to 3 years.',
                    'eligibility_requirements' => [
                        'South African citizen',
                        'Completed Matric or currently in Matric',
                        'Intending to study full-time towards one of the listed qualifications',
                        'Entering first year of undergraduate or Honours study in 2027',
                        'Intending to study at one of the listed public institutions in South Africa',
                        'Strong academic record',
                        'Financial need',
                        'Not receiving other funding, including NSFAS, bursary, scholarship or another award',
                        'Students with disabilities are encouraged to apply',
                        'Preference for previously disadvantaged students from poor and rural communities',
                    ],
                    'application_method' => 'Download the DWS bursary application form and submit the completed application by email to bursaries@dws.gov.za.',
                    'supporting_documents' => [
                        'Certified copy of ID document',
                        'Certified Grade 11 final results and latest Matric results, if currently in Matric',
                        'Certified copy of Matric certificate, if completed Matric',
                        'Proof of application, provisional acceptance or firm university offer for first-time students',
                        'Undergraduate academic record and proof of acceptance for first-year Honours students',
                        'Proof of parents or guardians income',
                    ],
                    'closing_date' => $closingDate,
                    'closing_date_label' => $closingDateLabel,
                    'contact_name' => 'Ms Nobulali Mtikitiki',
                    'contact_email' => 'MtikitikiN@dws.gov.za',
                    'contact_phone' => '012 336 7149',
                    'source_url' => 'https://www.zabursaries.co.za/government-bursaries-south-africa/department-of-water-sanitation-bursary/',
                    'apply_url' => 'https://www.dws.gov.za/learninga/Doc/2027%20DWS%20Internet%20bursary%20application-FINAL.pdf',
                ]),
            ),
        ];

        foreach ($bursaries as $entry) {
            $company = $entry['company'];
            $companySlug = Str::slug($company['name']);

            DB::table('companies')->updateOrInsert(
                ['slug' => $companySlug],
                [
                    'name' => $company['name'],
                    'website' => $company['website'],
                    'description' => $company['description'],
                    'contact_email' => $company['contact_email'],
                    'contact_phone' => $company['contact_phone'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
            );

            $companyId = DB::table('companies')->where('slug', $companySlug)->value('id');
            $bursary = $entry['bursary'];
            $bursarySlug = Str::slug($bursary['title']);

            DB::table('bursaries')->updateOrInsert(
                ['source_url' => $bursary['source_url']],
                [
                    'company_id' => $companyId,
                    'title' => $bursary['title'],
                    'slug' => $bursarySlug,
                    'category' => $bursary['category'],
                    'summary' => $bursary['summary'],
                    'fields_covered' => $bursary['fields_covered'],
                    'coverage_value' => $bursary['coverage_value'],
                    'service_contract' => $bursary['service_contract'],
                    'renewal' => $bursary['renewal'],
                    'eligibility_requirements' => json_encode($bursary['eligibility_requirements']),
                    'application_method' => $bursary['application_method'],
                    'supporting_documents' => json_encode($bursary['supporting_documents']),
                    'closing_date' => $bursary['closing_date'],
                    'closing_date_label' => $bursary['closing_date_label'],
                    'contact_name' => $bursary['contact_name'],
                    'contact_email' => $bursary['contact_email'],
                    'contact_phone' => $bursary['contact_phone'],
                    'apply_url' => $bursary['apply_url'],
                    'is_active' => $bursary['is_active'],
                    'updated_at' => $now,
                    'created_at' => $now,
                ],
            );

            $bursaryId = DB::table('bursaries')->where('source_url', $bursary['source_url'])->value('id');

            DB::table('bursary_subject_requirements')->where('bursary_id', $bursaryId)->delete();

            foreach ($entry['subject_requirements'] as $requirement) {
                DB::table('bursary_subject_requirements')->insert([
                    'bursary_id' => $bursaryId,
                    'subject_id' => $requirement['subject_id'] ?? null,
                    'grade_id' => $grade12Id,
                    'subject_name' => $requirement['subject_name'],
                    'minimum_mark' => $requirement['minimum_mark'] ?? null,
                    'aps_level_required' => $requirement['aps_level_required'] ?? null,
                    'requirement_type' => $requirement['requirement_type'] ?? 'required',
                    'requirement_group' => $requirement['requirement_group'] ?? null,
                    'notes' => $requirement['notes'] ?? null,
                    'created_at' => $now,
                    'updated_at' => $now,
                ]);
            }
        }
    }
}
