<?php

namespace App\Helpers;

class LookUp
{

    public const GENDERS_OPTIONS = [
        ['id' => 1, 'name' => 'Male'],
        ['id' => 2, 'name' => 'Female'],
        ['id' => 3, 'name' => 'Other']
    ];

    public const MARITAL_STATUS = [
        ['id' => 1, 'name' => 'Married'],
        ['id' => 2, 'name' => 'Single'],
        ['id' => 3, 'name' => 'Widow'],
        ['id' => 4, 'name' => 'Separated'],
        ['id' => 5, 'name' => 'Divorced']
    ];

    public const ETHNICITY_TYPES = [
        ['id' => 1, 'name' => 'Black'],
        ['id' => 2, 'name' => 'White'],
        ['id' => 3, 'name' => 'Colored'],
        ['id' => 4, 'name' => 'Asian']
    ];

    public const LANGAUGE_TYPES = [
        ['id' => 1, 'name' => 'English'],
        ['id' => 2, 'name' => 'Afrikaans'],
        ['id' => 3, 'name' => 'Southern Sotho'],
        ['id' => 4, 'name' => 'Northern Sotho'],
        ['id' => 5, 'name' => 'Swati'],
        ['id' => 6, 'name' => 'Tsonga'],
        ['id' => 7, 'name' => 'Venda'],
        ['id' => 8, 'name' => 'Xhosa'],
        ['id' => 9, 'name' => 'Zulu'],
    ];

    public const UNIT_TYPES = [
        ['id' => 1, 'active' => true, 'name' => 'Full Property', 'description' => 'Whole Property is for rental'],
        ['id' => 2, 'active' => true, 'name' => 'Room', 'description' => 'Individual room for rent'],
        ['id' => 3, 'active' => true, 'name' => 'Room Sharing', 'description' => 'Multiple tenant share room for rent'],
        ['id' => 4, 'active' => true, 'name' => 'Cottage', 'description' => 'Detached small house'],
        ['id' => 5, 'active' => true, 'name' => 'Apartment', 'description' => 'Unit in an apartment complex'],
        ['id' => 6, 'active' => true, 'name' => 'Others', 'description' => 'Others'],
    ];

    public const PROPERTY_TYPES = [
        ['id' => 1, 'active' => true, 'name' => 'House', 'description' => 'Standalone residential house'],
        ['id' => 2, 'active' => true, 'name' => 'Apartment', 'description' => 'Multi-unit residential building'],
        ['id' => 3, 'active' => true, 'name' => 'Townhouse', 'description' => 'Attached residential unit'],
        ['id' => 4, 'active' => true, 'name' => 'Studio', 'description' => 'Single-room residence'],
        ['id' => 5, 'active' => true, 'name' => 'Duplex', 'description' => 'Two-unit property'],
        ['id' => 6, 'active' => true, 'name' => 'Farm', 'description' => 'Plenty of acre land for rental'],
        ['id' => 7, 'active' => true, 'name' => 'Penthouse', 'description' => 'Luxury apartment on the top floor'],
    ];

    public const MAINTENANCE_TYPES = [
        [
            'id' => 1,
            'active' => true,
            'name' => 'Plumbing',
            'description' => 'Issues related to water supply, drains, and pipes',
        ],
        [
            'id' => 2,
            'active' => true,
            'name' => 'Electrical',
            'description' => 'Electrical repairs, rewiring, and fixture installations',
        ],
        [
            'id' => 3,
            'active' => true,
            'name' => 'HVAC',
            'description' => 'Heating, Ventilation, and Air Conditioning repairs',
        ],
        [
            'id' => 4,
            'active' => true,
            'name' => 'Carpentry',
            'description' => 'Woodwork, doors, windows, and structural fixes',
        ],
        [
            'id' => 5,
            'active' => true,
            'name' => 'Painting',
            'description' => 'Indoor and outdoor painting or refinishing',
        ],
        [
            'id' => 6,
            'active' => true,
            'name' => 'Landscaping',
            'description' => 'Garden, lawn, and outdoor maintenance',
        ],
        [
            'id' => 7,
            'active' => true,
            'name' => 'Appliances',
            'description' => 'Repairs or replacements of household appliances',
        ],
    ];


    public const COUNTRIES_OPTIONS = [
        ['id' => 1, 'name' => 'South Africa', 'nationality' => 'South African'],
    ];

    public const PROVINCES_OPTIONS = [
        ['id' => 1, 'name' => 'Gauteng', 'country_id' => 1],
    ];

    public const CITIES_OPTIONS = [
        ['id' => 1, 'name' => 'Pretoria', 'province_id' => 1],

    ];

    public const SUBURB_OPTIONS = [
        ['id' => 1, 'name' => 'Alphen Park', 'city_id' => 1],
        ['id' => 2, 'name' => 'Andeon', 'city_id' => 1],
        ['id' => 3, 'name' => 'Andeon AH', 'city_id' => 1],
        ['id' => 4, 'name' => 'Annlin', 'city_id' => 1],
        ['id' => 5, 'name' => 'Annlin-Wes', 'city_id' => 1],
        ['id' => 6, 'name' => 'Arcadia', 'city_id' => 1],
        ['id' => 7, 'name' => 'Ashlea Gardens', 'city_id' => 1],
        ['id' => 8, 'name' => 'Asiatic Bazaar', 'city_id' => 1],
        ['id' => 9, 'name' => 'Atteridgeville', 'city_id' => 1],
        ['id' => 10, 'name' => 'Baileys Muckleneuk', 'city_id' => 1],
        ['id' => 11, 'name' => 'Bashewa AH', 'city_id' => 1],
        ['id' => 12, 'name' => 'Baviaanspoort', 'city_id' => 1],
        ['id' => 13, 'name' => 'Berea Park', 'city_id' => 1],
        ['id' => 14, 'name' => 'Bergtuin', 'city_id' => 1],
        ['id' => 15, 'name' => 'Blue Crane Estate', 'city_id' => 1],
        ['id' => 16, 'name' => 'Blyde Riverwalk Estate', 'city_id' => 1],
        ['id' => 17, 'name' => 'Boardwalk', 'city_id' => 1],
        ['id' => 18, 'name' => 'Boardwalk Manor', 'city_id' => 1],
        ['id' => 19, 'name' => 'Boardwalk Meander', 'city_id' => 1],
        ['id' => 20, 'name' => 'Boardwalk Villas', 'city_id' => 1],
        ['id' => 21, 'name' => 'Bon Accord', 'city_id' => 1],
        ['id' => 22, 'name' => 'Booysens', 'city_id' => 1],
        ['id' => 23, 'name' => 'Boschkop AH', 'city_id' => 1],
        ['id' => 24, 'name' => 'Bougainvillea Estate', 'city_id' => 1],
        ['id' => 25, 'name' => 'Bronberg', 'city_id' => 1],
        ['id' => 26, 'name' => 'Bronberg Close', 'city_id' => 1],
        ['id' => 27, 'name' => 'Brooklyn', 'city_id' => 1],
        ['id' => 28, 'name' => 'Brummeria', 'city_id' => 1],
        ['id' => 29, 'name' => 'Buffelsdrift AH', 'city_id' => 1],
        ['id' => 30, 'name' => 'Capital Park', 'city_id' => 1],
        ['id' => 31, 'name' => 'Castle Gate', 'city_id' => 1],
        ['id' => 32, 'name' => 'Christiaanville AH', 'city_id' => 1],
        ['id' => 33, 'name' => 'Claremont', 'city_id' => 1],
        ['id' => 34, 'name' => 'Clearwater Flyfishing Estate', 'city_id' => 1],
        ['id' => 35, 'name' => 'Clydesdale', 'city_id' => 1],
        ['id' => 36, 'name' => 'Colbyn', 'city_id' => 1],
        ['id' => 37, 'name' => 'Constantia Park', 'city_id' => 1],
        ['id' => 38, 'name' => 'Country Lane Estate', 'city_id' => 1],
        ['id' => 39, 'name' => 'Country View Estate', 'city_id' => 1],
        ['id' => 40, 'name' => 'Cynthia Vale', 'city_id' => 1],
        ['id' => 41, 'name' => 'Danville', 'city_id' => 1],
        ['id' => 42, 'name' => 'Daspoort', 'city_id' => 1],
        ['id' => 43, 'name' => 'Deerness', 'city_id' => 1],
        ['id' => 44, 'name' => 'Derdepoort', 'city_id' => 1],
        ['id' => 45, 'name' => 'Despatch', 'city_id' => 1],
        ['id' => 46, 'name' => 'Die Wilgers', 'city_id' => 1],
        ['id' => 47, 'name' => 'Doornpoort', 'city_id' => 1],
        ['id' => 48, 'name' => 'Doornpoort AH', 'city_id' => 1],
        ['id' => 49, 'name' => 'Dorandia', 'city_id' => 1],
        ['id' => 50, 'name' => 'East Lynne', 'city_id' => 1],
        ['id' => 51, 'name' => 'Eastwood', 'city_id' => 1],
        ['id' => 52, 'name' => 'Eersterust', 'city_id' => 1],
        ['id' => 53, 'name' => 'Ekklesia', 'city_id' => 1],
        ['id' => 54, 'name' => 'Elandsfontein AH', 'city_id' => 1],
        ['id' => 55, 'name' => 'Elandspoort', 'city_id' => 1],
        ['id' => 56, 'name' => 'Elarduspark', 'city_id' => 1],
        ['id' => 57, 'name' => 'Eloffsdal', 'city_id' => 1],
        ['id' => 58, 'name' => 'Enormwater AH', 'city_id' => 1],
        ['id' => 59, 'name' => 'Equestria', 'city_id' => 1],
        ['id' => 60, 'name' => 'Erasmus Park', 'city_id' => 1],
        ['id' => 61, 'name' => 'Erasmuskloof', 'city_id' => 1],
        ['id' => 62, 'name' => 'Erasmusrand', 'city_id' => 1],
        ['id' => 63, 'name' => 'Faerie Glen', 'city_id' => 1],
        ['id' => 64, 'name' => 'Flora Park', 'city_id' => 1],
        ['id' => 65, 'name' => 'Florauna', 'city_id' => 1],
        ['id' => 66, 'name' => 'Fundus AH', 'city_id' => 1],
        ['id' => 67, 'name' => 'Garsfontein', 'city_id' => 1],
        ['id' => 68, 'name' => 'Gem Valley', 'city_id' => 1],
        ['id' => 69, 'name' => 'Georgeville', 'city_id' => 1],
        ['id' => 70, 'name' => 'Gezina', 'city_id' => 1],
        ['id' => 71, 'name' => 'Glenway Estate', 'city_id' => 1],
        ['id' => 72, 'name' => 'Greencreek Lifestyle Estate', 'city_id' => 1],
        ['id' => 73, 'name' => 'Groenkloof', 'city_id' => 1],
        ['id' => 74, 'name' => 'Grootfontein AH', 'city_id' => 1],
        ['id' => 75, 'name' => 'Grootfontein Country Estates', 'city_id' => 1],
        ['id' => 76, 'name' => 'Haakdoornlaagte AH', 'city_id' => 1],
        ['id' => 77, 'name' => 'Hatfield', 'city_id' => 1],
        ['id' => 78, 'name' => 'Hatherley AH', 'city_id' => 1],
        ['id' => 79, 'name' => 'Hazeldean', 'city_id' => 1],
        ['id' => 80, 'name' => 'Hazelwood', 'city_id' => 1],
        ['id' => 81, 'name' => 'Hercules', 'city_id' => 1],
        ['id' => 82, 'name' => 'Hermanstad', 'city_id' => 1],
        ['id' => 83, 'name' => 'Hillcrest', 'city_id' => 1],
        ['id' => 84, 'name' => 'Hornsoord AH', 'city_id' => 1],
        ['id' => 85, 'name' => 'Jan Niemand Park', 'city_id' => 1],
        ['id' => 86, 'name' => 'Jeffersville', 'city_id' => 1],
        ['id' => 87, 'name' => 'Kameeldrift East', 'city_id' => 1],
        ['id' => 88, 'name' => 'Kameeldrift West', 'city_id' => 1],
        ['id' => 89, 'name' => 'Kameelfontein', 'city_id' => 1],
        ['id' => 90, 'name' => 'Kenley AH', 'city_id' => 1],
        ['id' => 91, 'name' => 'Kilner Park', 'city_id' => 1],
        ['id' => 92, 'name' => 'Kirkney', 'city_id' => 1],
        ['id' => 93, 'name' => 'Kleinfontein AH', 'city_id' => 1],
        ['id' => 94, 'name' => 'Koedoespoort Industrial', 'city_id' => 1],
        ['id' => 95, 'name' => 'Krauseville AH', 'city_id' => 1],
        ['id' => 96, 'name' => 'Kwaggasrand', 'city_id' => 1],
        ['id' => 97, 'name' => 'La Concorde', 'city_id' => 1],
        ['id' => 98, 'name' => 'La Montagne', 'city_id' => 1],
        ['id' => 99, 'name' => 'Lady Selborne', 'city_id' => 1],
        ['id' => 100, 'name' => 'Leeuwenhof Estate', 'city_id' => 1],
        ['id' => 101, 'name' => 'Leeuwfontein', 'city_id' => 1],
        ['id' => 102, 'name' => 'Les Marais', 'city_id' => 1],
        ['id' => 103, 'name' => 'Lindo Park', 'city_id' => 1],
        ['id' => 104, 'name' => 'Lotus Gardens', 'city_id' => 1],
        ['id' => 105, 'name' => 'Lukasrand', 'city_id' => 1],
        ['id' => 106, 'name' => 'Lydiana', 'city_id' => 1],
        ['id' => 107, 'name' => 'Lynnrodene', 'city_id' => 1],
        ['id' => 108, 'name' => 'Lynnwood', 'city_id' => 1],
        ['id' => 109, 'name' => 'Lynnwood Glen', 'city_id' => 1],
        ['id' => 110, 'name' => 'Lynnwood Manor', 'city_id' => 1],
        ['id' => 111, 'name' => 'Lynnwood Park', 'city_id' => 1],
        ['id' => 112, 'name' => 'Lynnwood Ridge', 'city_id' => 1],
        ['id' => 113, 'name' => 'Magalieskruin', 'city_id' => 1],
        ['id' => 114, 'name' => 'Magaliesmoot AH', 'city_id' => 1],
        ['id' => 115, 'name' => 'Mahube Valley', 'city_id' => 1],
        ['id' => 116, 'name' => 'Mamelodi', 'city_id' => 1],
        ['id' => 117, 'name' => 'Maroelana', 'city_id' => 1],
        ['id' => 118, 'name' => 'Matejoane', 'city_id' => 1],
        ['id' => 119, 'name' => 'Mayville', 'city_id' => 1],
        ['id' => 120, 'name' => 'Menlo Park', 'city_id' => 1],
        ['id' => 121, 'name' => 'Menlyn', 'city_id' => 1],
        ['id' => 122, 'name' => 'Meyerspark', 'city_id' => 1],
        ['id' => 123, 'name' => 'Middelwater AH', 'city_id' => 1],
        ['id' => 124, 'name' => 'Mondustria', 'city_id' => 1],
        ['id' => 125, 'name' => 'Montana', 'city_id' => 1],
        ['id' => 126, 'name' => 'Montana Park', 'city_id' => 1],
        ['id' => 127, 'name' => 'Montana Tuine', 'city_id' => 1],
        ['id' => 128, 'name' => 'Monument Park', 'city_id' => 1],
        ['id' => 129, 'name' => 'Mooikloof', 'city_id' => 1],
        ['id' => 130, 'name' => 'Mooikloof Equestrian Estate', 'city_id' => 1],
        ['id' => 131, 'name' => 'Mooikloof Heights', 'city_id' => 1],
        ['id' => 132, 'name' => 'Mooikloof Ridge', 'city_id' => 1],
        ['id' => 133, 'name' => 'Mooiplaats AH', 'city_id' => 1],
        ['id' => 134, 'name' => 'Moregloed', 'city_id' => 1],
        ['id' => 135, 'name' => 'Moreleta Park', 'city_id' => 1],
        ['id' => 136, 'name' => 'Mountain View', 'city_id' => 1],
        ['id' => 137, 'name' => 'Muckleneuk', 'city_id' => 1],
        ['id' => 138, 'name' => 'Murrayfield', 'city_id' => 1],
        ['id' => 139, 'name' => 'N4 Gateway Industrial Park', 'city_id' => 1],
        ['id' => 140, 'name' => 'Nellmapius', 'city_id' => 1],
        ['id' => 141, 'name' => 'Newlands', 'city_id' => 1],
        ['id' => 142, 'name' => 'Newmark Estate', 'city_id' => 1],
        ['id' => 143, 'name' => 'Nieuw Muckleneuk', 'city_id' => 1],
        ['id' => 144, 'name' => 'Olympus AH', 'city_id' => 1],
        ['id' => 145, 'name' => 'Olympus Heights Estate', 'city_id' => 1],
        ['id' => 146, 'name' => 'Olympus Ridge', 'city_id' => 1],
        ['id' => 147, 'name' => 'Onderstepoort', 'city_id' => 1],
        ['id' => 148, 'name' => 'Paradiso', 'city_id' => 1],
        ['id' => 149, 'name' => 'Paramount Estate', 'city_id' => 1],
        ['id' => 150, 'name' => 'Parktown Estate', 'city_id' => 1],
        ['id' => 151, 'name' => 'Patryshoek AH', 'city_id' => 1],
        ['id' => 152, 'name' => 'Pebble Rock Golf Village', 'city_id' => 1],
        ['id' => 153, 'name' => 'Persequor', 'city_id' => 1],
        ['id' => 154, 'name' => 'Philip Nel Park', 'city_id' => 1],
        ['id' => 155, 'name' => 'Phumolong', 'city_id' => 1],
        ['id' => 156, 'name' => 'Pretoria Central', 'city_id' => 1],
        ['id' => 157, 'name' => 'Pretoria Gardens', 'city_id' => 1],
        ['id' => 158, 'name' => 'Pretoria Industrial', 'city_id' => 1],
        ['id' => 159, 'name' => 'Pretoria North', 'city_id' => 1],
        ['id' => 160, 'name' => 'Pretoria West', 'city_id' => 1],
        ['id' => 160, 'name' => 'Pretoria West', 'city_id' => 1],
        ['id' => 161, 'name' => 'Pretoriuspark', 'city_id' => 1],
        ['id' => 162, 'name' => 'Prinshof', 'city_id' => 1],
        ['id' => 163, 'name' => 'Proclamation Hill', 'city_id' => 1],
        ['id' => 164, 'name' => 'Pumulani', 'city_id' => 1],
        ['id' => 165, 'name' => 'Queenswood', 'city_id' => 1],
        ['id' => 166, 'name' => 'Rhenosterfontein AH', 'city_id' => 1],
        ['id' => 167, 'name' => 'Rietfontein', 'city_id' => 1],
        ['id' => 168, 'name' => 'Rietfontein SH', 'city_id' => 1],
        ['id' => 169, 'name' => 'Rietondale', 'city_id' => 1],
        ['id' => 170, 'name' => 'Rietvallei AH', 'city_id' => 1],
        ['id' => 171, 'name' => 'Rietvalleirand', 'city_id' => 1],
        ['id' => 172, 'name' => 'Rietvlei Heights Country Estate', 'city_id' => 1],
        ['id' => 173, 'name' => 'Rietvlei Ridge Country Estate', 'city_id' => 1],
        ['id' => 174, 'name' => 'Rietvlei View Country Estates', 'city_id' => 1],
        ['id' => 175, 'name' => 'Riviera', 'city_id' => 1],
        ['id' => 176, 'name' => 'Roodeplaat', 'city_id' => 1],
        ['id' => 177, 'name' => 'Roseville', 'city_id' => 1],
        ['id' => 178, 'name' => 'Sable Hills', 'city_id' => 1],
        ['id' => 179, 'name' => 'Salieshoek', 'city_id' => 1],
        ['id' => 180, 'name' => 'Salvokop', 'city_id' => 1],
        ['id' => 181, 'name' => 'Samcor Park', 'city_id' => 1],
        ['id' => 182, 'name' => 'Saulsville', 'city_id' => 1],
        ['id' => 183, 'name' => 'Savannah Country Estate', 'city_id' => 1],
        ['id' => 184, 'name' => 'Schurveberg AH', 'city_id' => 1],
        ['id' => 185, 'name' => 'Scientia', 'city_id' => 1],
        ['id' => 186, 'name' => 'Shere', 'city_id' => 1],
        ['id' => 187, 'name' => 'Siahlala', 'city_id' => 1],
        ['id' => 188, 'name' => 'Silver Lakes', 'city_id' => 1],
        ['id' => 189, 'name' => 'Silver Stream Estate', 'city_id' => 1],
        ['id' => 190, 'name' => 'Silverton', 'city_id' => 1],
        ['id' => 191, 'name' => 'Silverwoods Country Estate', 'city_id' => 1],
        ['id' => 192, 'name' => 'Sinoville', 'city_id' => 1],
        ['id' => 193, 'name' => 'Six Fountains', 'city_id' => 1],
        ['id' => 194, 'name' => 'Sterrewag', 'city_id' => 1],
        ['id' => 195, 'name' => 'Strydfontein AH', 'city_id' => 1],
        ['id' => 196, 'name' => 'Suiderberg', 'city_id' => 1],
        ['id' => 197, 'name' => 'Sunnyside', 'city_id' => 1],
        ['id' => 198, 'name' => 'Sunset View AH', 'city_id' => 1],
        ['id' => 199, 'name' => 'Swacina Park AH', 'city_id' => 1],
        ['id' => 200, 'name' => 'The Hills Game Reserve Estate', 'city_id' => 1],
        ['id' => 201, 'name' => 'The Wilds', 'city_id' => 1],
        ['id' => 202, 'name' => 'The Willows', 'city_id' => 1],
        ['id' => 203, 'name' => 'Tiegerpoort AH', 'city_id' => 1],
        ['id' => 204, 'name' => 'Tijger Vallei', 'city_id' => 1],
        ['id' => 205, 'name' => 'Tileba', 'city_id' => 1],
        ['id' => 206, 'name' => 'Trevenna', 'city_id' => 1],
        ['id' => 207, 'name' => 'Tyger Valley', 'city_id' => 1],
        ['id' => 208, 'name' => 'Uitzicht AH', 'city_id' => 1],
        ['id' => 209, 'name' => 'Val De Grace', 'city_id' => 1],
        ['id' => 210, 'name' => 'Vergenoeg', 'city_id' => 1],
        ['id' => 211, 'name' => 'Verresig Country Estate', 'city_id' => 1],
        ['id' => 212, 'name' => 'Villieria', 'city_id' => 1],
        ['id' => 213, 'name' => 'Vissershoek AH', 'city_id' => 1],
        ['id' => 214, 'name' => 'Vrede AH', 'city_id' => 1],
        ['id' => 215, 'name' => 'Waltloo', 'city_id' => 1],
        ['id' => 216, 'name' => 'Wapadrand', 'city_id' => 1],
        ['id' => 217, 'name' => 'Waterkloof', 'city_id' => 1],
        ['id' => 218, 'name' => 'Waterkloof Glen', 'city_id' => 1],
        ['id' => 219, 'name' => 'Waterkloof Heights', 'city_id' => 1],
        ['id' => 220, 'name' => 'Waterkloof Park', 'city_id' => 1],
        ['id' => 221, 'name' => 'Waterkloof Ridge', 'city_id' => 1],
        ['id' => 222, 'name' => 'Waterlake Farm Lifestyle Estate', 'city_id' => 1],
        ['id' => 223, 'name' => 'Waverley', 'city_id' => 1],
        ['id' => 224, 'name' => 'Weavind Park', 'city_id' => 1],
        ['id' => 225, 'name' => 'West Park', 'city_id' => 1],
        ['id' => 226, 'name' => 'Wildebeeshoek AH', 'city_id' => 1],
        ['id' => 227, 'name' => 'Willow Acres', 'city_id' => 1],
        ['id' => 228, 'name' => 'Willow Park Manor', 'city_id' => 1],
        ['id' => 229, 'name' => 'Wingate Park', 'city_id' => 1],
        ['id' => 230, 'name' => 'Wolmaranspoort AH', 'city_id' => 1],
        ['id' => 231, 'name' => 'Wolmer', 'city_id' => 1],
        ['id' => 232, 'name' => 'Wonderboom', 'city_id' => 1],
        ['id' => 233, 'name' => 'Wonderboom AH', 'city_id' => 1],
        ['id' => 234, 'name' => 'Wonderboom South', 'city_id' => 1],
        ['id' => 235, 'name' => 'Woodhill Golf Estate', 'city_id' => 1],
        ['id' => 236, 'name' => 'Woodlands Lifestyle Estate', 'city_id' => 1],
        ['id' => 237, 'name' => 'Zambezi Country Estate', 'city_id' => 1],
        ['id' => 238, 'name' => 'Zambezi Manor Lifestyle Estate', 'city_id' => 1],
        ['id' => 239, 'name' => 'Zandfontein AH', 'city_id' => 1],
        ['id' => 240, 'name' => 'Zwartkoppies', 'city_id' => 1],
        ['id' => 241, 'name' => 'Zwavelpoort AH', 'city_id' => 1],
    ];

}
